racaoKg = float(input("Digite a quantidade de ração em kilos\n"))
gato1 = float(input("Digite a quantidade de ração para o gato 1 em gramas\n"))
gato2 = float(input("Digite a quantidade de ração para o gato 2 em gramas\n"))
quant = (racaoKg * 1000) - ((gato1 + gato2)* 5)
print("Restará de ração",round(quant, 2))
